action_time: 0.01
bullet_time_step: 0.001
env_id: SnakeLocomotionDiscrete-v0
max_torque_rate: 100
observation_flags:
  target_pos:
  positions: 32
  velocities: 32
  error:
  # error_distance:
  # error_direction:
  # angles: 4
  # curvatures: 4
  applied_input_torques:
reward_flags:
  head_target_dist: -10
torque_multiplier: 80 # todo: double check what this value should be
difficulty: basic